sudo: false
language: php

cache:
    directories:
        - $HOME/.composer/cache

matrix:
  include:
    - php: 5.3
      dist: trusty

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

install:
    composer install --prefer-dist --no-interaction

before_script:
    - mkdir -p build/logs

script:
    phpunit --coverage-clover build/logs/clover.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar -t 3
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
